const https=require('https'),{normalizeSymbol}=require('./symbol'),{decodeUpstreamResponse,jsonp}=require('../utils/decode-upstream')
class UpstreamError extends Error{constructor(code,message,retryable=true){super(message);this.code=code;this.retryable=retryable}}
const request=(url,source)=>new Promise((resolve,reject)=>{const started=Date.now();const r=https.get(url,{headers:{'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/120 Safari/537.36','Referer':'https://quote.eastmoney.com/','Accept':'application/json,text/plain,*/*'}},res=>{const chunks=[];res.on('data',d=>chunks.push(d));res.on('end',()=>{const buffer=Buffer.concat(chunks),meta={status:res.statusCode,contentType:res.headers['content-type']||'',contentEncoding:res.headers['content-encoding']||'',bytes:buffer.length,durationMs:Date.now()-started};if(res.statusCode<200||res.statusCode>=300)return reject(new UpstreamError('UPSTREAM_HTTP_'+res.statusCode,'Upstream HTTP '+res.statusCode));const decoded=decodeUpstreamResponse({buffer,contentType:meta.contentType,source});resolve({...decoded,meta})})});r.setTimeout(8000,()=>r.destroy(new UpstreamError('UPSTREAM_TIMEOUT','Upstream timeout')));r.on('error',e=>reject(e instanceof UpstreamError?e:new UpstreamError('UPSTREAM_NETWORK',e.message)) )})
const parse=async(url,source)=>{const r=await request(url,source);if(r.isHtml)throw new UpstreamError('UPSTREAM_HTML','Upstream returned HTML');try{return JSON.parse(jsonp(r.text))}catch{throw new UpstreamError('UPSTREAM_PARSE','Upstream returned invalid JSON')}}
const secid=s=>`${s.market==='SH'?'1':'0'}.${s.code}`
async function capitalFlow(s){const j=await parse(`https://push2his.eastmoney.com/api/qt/stock/fflow/daykline/get?lmt=1&klt=101&secid=${secid(s)}&fields1=f1,f2,f3,f7&fields2=f51,f52,f53,f54,f55,f56,f57,f58,f59,f60,f61,f62,f63`,'eastmoney');const v=j?.data?.klines?.[0]?.split(',');if(!v)throw new UpstreamError('EMPTY_FLOW','No capital-flow record',false);return {symbol:s.code,main:Number(v[1]),superLarge:Number(v[2]),large:Number(v[3]),medium:Number(v[4]),small:Number(v[5]),source:'Eastmoney fund flow'}}
async function disclosures(s,limit){const j=await parse(`https://np-anotice-stock.eastmoney.com/api/security/ann?sr=-1&page_size=${limit}&page_index=1&ann_type=A&client_source=web&stock_list=${s.code}`,'disclosures');return {symbol:s.code,items:(j?.data?.list||[]).map(x=>({title:x.title||'',date:String(x.notice_date||x.display_time||'').slice(0,10),columns:(x.columns||[]).map(c=>c.column_name).join('/'),url:`https://data.eastmoney.com/notices/detail/${s.code}/${x.art_code||''}.html`})).filter(x=>x.title),source:'Eastmoney announcements'}}
async function tencent(codes,source,encodingSource='tencentQuote'){const r=await request('https://qt.gtimg.cn/q='+codes.join(','),encodingSource);const rows=r.text.split(';').map(x=>{const m=x.match(/v_([^=]+)="([^"]*)/);if(!m)return null;const a=m[2].split('~');return {symbol:m[1],name:a[1]||'',price:Number(a[3]),previousClose:Number(a[4]),changePercent:Number(a[32]),quoteTime:a[30]||''}}).filter(Boolean);return {items:rows,source}}
async function fundamentals(s){const r=await tencent([s.upstream],'Tencent quote fundamentals');const x=r.items[0];if(!x||!Number.isFinite(x.price))throw new UpstreamError('EMPTY_FUNDAMENTALS','No fundamentals quote',false);return {...x,symbol:s.code,pe:null,pb:null,marketCap:null,source:r.source}}
const domestic=()=>tencent(['sh000001','sz399001','sz399006'],'Tencent domestic indices','domesticIndices')
const global=()=>tencent(['usIXIC','hkHSI'],'Tencent global indices','globalIndices')
async function news(s,limit){const j=await parse(`https://search-api-web.eastmoney.com/search/jsonp?param=%7B%22uid%22%3A%22%22%2C%22keyword%22%3A%22${encodeURIComponent(s.code)}%22%2C%22type%22%3A%5B%22cmsArticleWebOld%22%5D%2C%22pageindex%22%3A1%2C%22pagesize%22%3A${limit}%7D`,'news');const list=j?.result?.cmsArticleWebOld||[];if(!list.length)throw new UpstreamError('EMPTY_NEWS','No news record',false);return {symbol:s.code,items:list.map(x=>({title:x.title,date:x.date||'',source:x.mediaName||'Eastmoney',url:x.url||''})),source:'Eastmoney news search'}}
module.exports={capitalFlow,disclosures,fundamentals,domestic,global,news,UpstreamError,request}
