const https = require('https'), iconv = require('iconv-lite')
const { parseTencentQuote } = require('./parsers')
function upstream(url) { return new Promise((resolve,reject)=>{const req=https.get(url,{headers:{'User-Agent':'Mozilla/5.0 stock-analysis-local-proxy'},timeout:8000},res=>{let chunks=[];res.on('data',c=>chunks.push(c));res.on('end',()=>res.statusCode===200?resolve(iconv.decode(Buffer.concat(chunks),'gbk')):reject(new Error(`UPSTREAM_HTTP_${res.statusCode}`)))});req.on('timeout',()=>req.destroy(new Error('UPSTREAM_TIMEOUT')));req.on('error',reject)}) }
async function getQuote(symbol) { return parseTencentQuote(await upstream(`https://qt.gtimg.cn/q=${symbol.upstream}`), symbol) }
function json(url) { return new Promise((resolve,reject)=>{const req=https.get(url,{headers:{'User-Agent':'Mozilla/5.0 stock-analysis-local-proxy'},timeout:8000},res=>{let b='';res.on('data',x=>b+=x);res.on('end',()=>{try{res.statusCode===200?resolve(JSON.parse(b)):reject(new Error(`UPSTREAM_HTTP_${res.statusCode}`))}catch{reject(new Error('UPSTREAM_INVALID_JSON'))}})});req.on('timeout',()=>req.destroy(new Error('UPSTREAM_TIMEOUT')));req.on('error',reject)}) }
function continuous(time){const n=Number(String(time).replace(':',''));return (n>=931&&n<=1130)||(n>=1300&&n<=1500)}
async function getMinute(symbol){const q=await getQuote(symbol),j=await json(`https://web.ifzq.gtimg.cn/appstock/app/minute/query?code=${symbol.upstream}`),raw=j?.data?.[symbol.upstream]?.data?.data||[];const points=raw.map(row=>{const a=String(row).split(' ');return {time:a[0],price:Number(a[1]),volume:Number(a[2]),amount:Number(a[3])}}).filter(x=>Number.isFinite(x.price)&&x.price>0&&continuous(x.time));if(points.length<1)throw new Error('UPSTREAM_EMPTY');let totalVolume=0,totalAmount=0;return {symbol:symbol.code,market:symbol.market,name:q.name,previousClose:q.previousClose,tradingDate:q.quoteTime.slice(0,8),points:points.map(x=>{totalVolume+=x.volume||0;totalAmount+=x.amount||0;return {...x,averagePrice:totalVolume?totalAmount/totalVolume:null}}),source:'Tencent minute',quoteTime:q.quoteTime} }
async function getDaily(symbol,count){const q=await getQuote(symbol),j=await json(`https://web.ifzq.gtimg.cn/appstock/app/fqkline/get?param=${symbol.upstream},day,,,${count},qfq`),box=j?.data?.[symbol.upstream],raw=box?.qfqday||box?.day||[];const rows=raw.map(a=>({date:a[0],open:Number(a[1]),close:Number(a[2]),high:Number(a[3]),low:Number(a[4]),volume:Number(a[5])})).filter(x=>Number.isFinite(x.close)&&x.close>0);if(!rows.length)throw new Error('UPSTREAM_EMPTY');return {symbol:symbol.code,market:symbol.market,name:q.name,rows,source:'Tencent qfq kline',quoteTime:q.quoteTime} }
async function getOrderbook(symbol){const q=await getQuote(symbol);const bid=q.book?.filter(x=>x.side==='bid')||[],ask=q.book?.filter(x=>x.side==='ask')||[];return {symbol:symbol.code,market:symbol.market,name:q.name,bids:bid,asks:ask,spread:bid[0]&&ask[0]?ask[0].price-bid[0].price:null,source:'Tencent quote',quoteTime:q.quoteTime} }
module.exports = { getQuote, getMinute, getDaily, getOrderbook }
